import { getAddress, type Address } from 'viem'

import type { EvidenceLevel } from '../domain/types.js'

export type NetworkId = 'base' | 'robinhood' | 'bnb'
export type ContractSupport =
  'DISCOVERY_ONLY' | 'PLANNED_ADAPTER' | 'REGISTRY_ONLY' | 'LIVE_ADAPTER'

export interface NetworkDefinition {
  readonly id: NetworkId
  readonly name: string
  readonly chainId: number
  readonly publicHttpRpc: string
  readonly publicWebSocketRpc?: string
  readonly pendingStateHttpRpc?: string
  readonly pendingStateWebSocketRpc?: string
  readonly rpcEvidenceUrl: string
  readonly notes: readonly string[]
}

export interface ContractDefinition {
  readonly id: string
  readonly network: NetworkId
  readonly protocolId: string
  readonly venueId: string | null
  readonly platformId: string | null
  readonly role: string
  readonly address: Address
  readonly support: ContractSupport
  readonly evidenceLevel: EvidenceLevel
  readonly evidenceUrl: string
}

const address = (value: string): Address => getAddress(value)

export const NETWORKS: Readonly<Record<NetworkId, NetworkDefinition>> = {
  base: {
    id: 'base',
    name: 'Base Mainnet',
    chainId: 8453,
    publicHttpRpc: 'https://mainnet.base.org',
    publicWebSocketRpc: 'wss://mainnet.base.org',
    pendingStateHttpRpc: 'https://mainnet-preconf.base.org',
    pendingStateWebSocketRpc: 'wss://mainnet-preconf.base.org',
    rpcEvidenceUrl: 'https://docs.base.org/base-chain/api-reference/rpc-overview',
    notes: [
      'The official public endpoint is rate limited and is not a production SLA.',
      'Flashblocks pending state is a separate capability and must retain its sequence identity.',
    ],
  },
  robinhood: {
    id: 'robinhood',
    name: 'Robinhood Chain Mainnet',
    chainId: 4663,
    publicHttpRpc: 'https://rpc.mainnet.chain.robinhood.com',
    rpcEvidenceUrl: 'https://docs.robinhood.com/crypto/Robinhood-Chain/overview/',
    notes: [
      'Initial contract identities are repository records from the existing Robinhood engine.',
      'PAIR and LONG_ROUTE remain discovery/platform dimensions, never implicit venue identities.',
    ],
  },
  bnb: {
    id: 'bnb',
    name: 'BNB Smart Chain Mainnet',
    chainId: 56,
    publicHttpRpc: 'https://bsc-dataseed.bnbchain.org',
    rpcEvidenceUrl:
      'https://docs.bnbchain.org/bnb-smart-chain/developers/json_rpc/json-rpc-endpoint/',
    notes: [
      'The official public endpoint is suitable only for bounded read probes and is not a production SLA.',
      'Public endpoints disable eth_getLogs; persistent discovery must use a measured WebSocket, indexer, or bounded provider lane.',
      'MEV/PBS builder competition is part of execution economics and is not solved by pool discovery.',
    ],
  },
}

const UNISWAP_V3_BASE_SOURCE =
  'https://developers.uniswap.org/docs/protocols/v3/deployments/v3-base-deployments'
const UNISWAP_V4_SOURCE = 'https://developers.uniswap.org/docs/protocols/v4/deployments'
const AERODROME_SOURCE = 'https://aerodrome.finance/security'
const AERODROME_REGISTRY_SOURCE =
  'https://github.com/aerodrome-finance/contracts/blob/main/contracts/FactoryRegistry.sol'
const PANCAKE_V3_SOURCE = 'https://developer.pancakeswap.finance/contracts/v3/addresses'
const PANCAKE_V2_SOURCE = 'https://developer.pancakeswap.finance/contracts/v2/addresses'
const UNISWAP_V2_SOURCE = 'https://developers.uniswap.org/docs/protocols/v2/deployments'
const UNISWAP_V3_BNB_SOURCE =
  'https://developers.uniswap.org/docs/protocols/v3/deployments/v3-bnb-deployments'
const UNISWAP_V3_ROBINHOOD_SOURCE =
  'https://developers.uniswap.org/docs/protocols/v3/deployments/v3-robinhood-chain-deployments'
const EARNONHOOD_SOURCE = 'https://earnonhood.com/docs'

export const CONTRACTS: readonly ContractDefinition[] = [
  {
    id: 'base.uniswap-v2.factory',
    network: 'base',
    protocolId: 'UNISWAP_V2',
    venueId: 'UNISWAP_V2',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6'),
    support: 'LIVE_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: 'https://github.com/Uniswap/util-contracts',
  },
  {
    id: 'base.uniswap-v3.factory',
    network: 'base',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x33128a8fC17869897dcE68Ed026d694621f6FDfD'),
    support: 'LIVE_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_BASE_SOURCE,
  },
  {
    id: 'base.uniswap-v3.quoter-v2',
    network: 'base',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'QUOTER',
    address: address('0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a'),
    support: 'LIVE_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_BASE_SOURCE,
  },
  {
    id: 'base.uniswap-v3.swap-router-02',
    network: 'base',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'ROUTER',
    address: address('0x2626664c2603336E57B271c5C0b26F421741e481'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_BASE_SOURCE,
  },
  {
    id: 'base.uniswap-v4.pool-manager',
    network: 'base',
    protocolId: 'UNISWAP_V4',
    venueId: 'UNISWAP_V4',
    platformId: null,
    role: 'POOL_MANAGER',
    address: address('0x498581ff718922c3f8e6a244956af099b2652b2b'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V4_SOURCE,
  },
  {
    id: 'base.uniswap-v4.quoter',
    network: 'base',
    protocolId: 'UNISWAP_V4',
    venueId: 'UNISWAP_V4',
    platformId: null,
    role: 'QUOTER',
    address: address('0x0d5e0f971ed27fbff6c2837bf31316121532048d'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V4_SOURCE,
  },
  {
    id: 'base.uniswap-v4.state-view',
    network: 'base',
    protocolId: 'UNISWAP_V4',
    venueId: 'UNISWAP_V4',
    platformId: null,
    role: 'STATE_VIEW',
    address: address('0xa3c0c9b65bad0b08107aa264b0f3db444b867a71'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V4_SOURCE,
  },
  {
    id: 'base.uniswap-v4.universal-router',
    network: 'base',
    protocolId: 'UNISWAP_V4',
    venueId: 'UNISWAP_V4',
    platformId: null,
    role: 'ROUTER',
    address: address('0x6ff5693b99212da76ad316178a184ab56d299b43'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V4_SOURCE,
  },
  {
    id: 'base.aerodrome.factory-registry',
    network: 'base',
    protocolId: 'AERODROME',
    venueId: null,
    platformId: null,
    role: 'FACTORY_REGISTRY',
    address: address('0x5C3F18F06CC09CA1910767A34a20F771039E37C0'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: AERODROME_REGISTRY_SOURCE,
  },
  {
    id: 'base.aerodrome.pool-factory',
    network: 'base',
    protocolId: 'AERODROME',
    venueId: 'AERODROME_STANDARD',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x420DD381b31aEf6683db6B902084cB0FFECe40Da'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: AERODROME_SOURCE,
  },
  {
    id: 'base.aerodrome.router',
    network: 'base',
    protocolId: 'AERODROME',
    venueId: 'AERODROME_STANDARD',
    platformId: null,
    role: 'ROUTER',
    address: address('0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: AERODROME_SOURCE,
  },
  {
    id: 'base.aerodrome-slipstream.pool-factory',
    network: 'base',
    protocolId: 'AERODROME_SLIPSTREAM',
    venueId: 'AERODROME_SLIPSTREAM',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: AERODROME_SOURCE,
  },
  {
    id: 'base.aerodrome-slipstream.pool-factory-v2',
    network: 'base',
    protocolId: 'AERODROME_SLIPSTREAM',
    venueId: 'AERODROME_SLIPSTREAM',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0xaDe65c38CD4849aDBA595a4323a8C7DdfE89716a'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'live_observed',
    evidenceUrl: AERODROME_REGISTRY_SOURCE,
  },
  {
    id: 'base.aerodrome-slipstream.pool-factory-v3',
    network: 'base',
    protocolId: 'AERODROME_SLIPSTREAM',
    venueId: 'AERODROME_SLIPSTREAM',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0xf8f2eB4940CFE7d13603DDDD87f123820Fc061Ef'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'live_observed',
    evidenceUrl: AERODROME_REGISTRY_SOURCE,
  },
  {
    id: 'base.aerodrome-slipstream.quoter',
    network: 'base',
    protocolId: 'AERODROME_SLIPSTREAM',
    venueId: 'AERODROME_SLIPSTREAM',
    platformId: null,
    role: 'QUOTER',
    address: address('0x254cF9E1E6e233aa1AC962CB9B05b2cfeAaE15b0'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: AERODROME_SOURCE,
  },
  {
    id: 'base.aerodrome-slipstream.swap-router',
    network: 'base',
    protocolId: 'AERODROME_SLIPSTREAM',
    venueId: 'AERODROME_SLIPSTREAM',
    platformId: null,
    role: 'ROUTER',
    address: address('0xBE6D8f0d05cC4be24d5167a3eF062215bE6D18a5'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: AERODROME_SOURCE,
  },
  {
    id: 'base.pancakeswap-v3.factory',
    network: 'base',
    protocolId: 'PANCAKESWAP_V3',
    venueId: 'PANCAKESWAP_V3',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865'),
    support: 'LIVE_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V3_SOURCE,
  },
  {
    id: 'base.pancakeswap-v3.quoter-v2',
    network: 'base',
    protocolId: 'PANCAKESWAP_V3',
    venueId: 'PANCAKESWAP_V3',
    platformId: null,
    role: 'QUOTER',
    address: address('0xB048Bbc1Ee6b733FFfCFb9e9CeF7375518e25997'),
    support: 'LIVE_ADAPTER',
    evidenceLevel: 'live_observed',
    evidenceUrl: PANCAKE_V3_SOURCE,
  },
  {
    id: 'robinhood.uniswap-v3.factory',
    network: 'robinhood',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x1f7d7550B1b028f7571E69A784071F0205FD2EfA'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_ROBINHOOD_SOURCE,
  },
  {
    id: 'robinhood.uniswap-v3.quoter',
    network: 'robinhood',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'QUOTER',
    address: address('0x33e885ed0ec9bf04ecfb19341582aadcb4c8a9e7'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_ROBINHOOD_SOURCE,
  },
  {
    id: 'robinhood.uniswap-v3.router',
    network: 'robinhood',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'ROUTER',
    address: address('0xCaf681a66D020601342297493863E78C959E5cb2'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_ROBINHOOD_SOURCE,
  },
  {
    id: 'robinhood.uniswap-v4.pool-manager',
    network: 'robinhood',
    protocolId: 'UNISWAP_V4',
    venueId: 'UNISWAP_V4',
    platformId: null,
    role: 'POOL_MANAGER',
    address: address('0x8366a39CC670B4001A1121B8F6A443A643e40951'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V4_SOURCE,
  },
  {
    id: 'robinhood.uniswap-v2.factory',
    network: 'robinhood',
    protocolId: 'UNISWAP_V2',
    venueId: 'UNISWAP_V2',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x8bceaa40b9acdfaedf85adf4ff01f5ad6517937f'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V2_SOURCE,
  },
  {
    id: 'robinhood.uniswap-v2.router',
    network: 'robinhood',
    protocolId: 'UNISWAP_V2',
    venueId: 'UNISWAP_V2',
    platformId: null,
    role: 'ROUTER',
    address: address('0x89e5db8b5aa49aa85ac63f691524311aeb649eba'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V2_SOURCE,
  },
  {
    id: 'robinhood.pancakeswap-v2.factory',
    network: 'robinhood',
    protocolId: 'PANCAKESWAP_V2',
    venueId: 'PANCAKESWAP_V2',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x02a84c1b3BBD7401a5f7fa98a384EBC70bB5749E'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V2_SOURCE,
  },
  {
    id: 'robinhood.pancakeswap-v2.router',
    network: 'robinhood',
    protocolId: 'PANCAKESWAP_V2',
    venueId: 'PANCAKESWAP_V2',
    platformId: null,
    role: 'ROUTER',
    address: address('0x8cFe327CEc66d1C090Dd72bd0FF11d690C33a2Eb'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V2_SOURCE,
  },
  {
    id: 'robinhood.pancakeswap-v3.factory',
    network: 'robinhood',
    protocolId: 'PANCAKESWAP_V3',
    venueId: 'PANCAKESWAP_V3',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V3_SOURCE,
  },
  {
    id: 'robinhood.pancakeswap-v3.quoter-v2',
    network: 'robinhood',
    protocolId: 'PANCAKESWAP_V3',
    venueId: 'PANCAKESWAP_V3',
    platformId: null,
    role: 'QUOTER',
    address: address('0x8553AA1615549A86882151784b329B017aA7c832'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V3_SOURCE,
  },
  {
    id: 'robinhood.earn.vault',
    network: 'robinhood',
    protocolId: 'BALANCER_V3',
    venueId: 'EARN_BALANCER_V3',
    platformId: 'EARNONHOOD',
    role: 'VAULT',
    address: address('0x28082618Ba2073E602230188E4F4C46e9b2169EB'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'live_observed',
    evidenceUrl: EARNONHOOD_SOURCE,
  },
  {
    id: 'robinhood.earn.batch-router',
    network: 'robinhood',
    protocolId: 'BALANCER_V3',
    venueId: 'EARN_BALANCER_V3',
    platformId: 'EARNONHOOD',
    role: 'QUOTER_AND_ROUTER',
    address: address('0x2d6DD5A990a643A8B11CD06554FBC290a1a82bA6'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'live_observed',
    evidenceUrl: EARNONHOOD_SOURCE,
  },
  {
    id: 'robinhood.earn.hood-ecosystem-pool',
    network: 'robinhood',
    protocolId: 'BALANCER_V3',
    venueId: 'EARN_BALANCER_V3',
    platformId: 'EARNONHOOD',
    role: 'POOL',
    address: address('0x4188656eAFdD7634d35Ca3f98ddfBf4b403A41fA'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'live_observed',
    evidenceUrl: EARNONHOOD_SOURCE,
  },
  {
    id: 'robinhood.earn.stock-memes-pool',
    network: 'robinhood',
    protocolId: 'BALANCER_V3',
    venueId: 'EARN_BALANCER_V3',
    platformId: 'EARNONHOOD',
    role: 'POOL',
    address: address('0x00e7B76d0C0F0370C28A07aA9d9fDF92736238A6'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'live_observed',
    evidenceUrl: EARNONHOOD_SOURCE,
  },
  {
    id: 'robinhood.earn.long-eco-pool',
    network: 'robinhood',
    protocolId: 'BALANCER_V3',
    venueId: 'EARN_BALANCER_V3',
    platformId: 'EARNONHOOD',
    role: 'POOL',
    address: address('0xcDe242535A75F8ccB5D4b14686e312c196B28855'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'live_observed',
    evidenceUrl: EARNONHOOD_SOURCE,
  },
  {
    id: 'robinhood.long.launcher',
    network: 'robinhood',
    protocolId: 'DOPPLER',
    venueId: null,
    platformId: 'LONG_ROUTE',
    role: 'UNIQUE_PLATFORM_ENTRY',
    address: address('0x22e99278308b393ea1260859b181ad7e78f5eeed'),
    support: 'DISCOVERY_ONLY',
    evidenceLevel: 'repository_record',
    evidenceUrl: 'https://docs.robinhood.com/chain/',
  },
  {
    id: 'robinhood.pair.hook',
    network: 'robinhood',
    protocolId: 'UNKNOWN',
    venueId: 'UNISWAP_V4',
    platformId: 'PAIR',
    role: 'PLATFORM_LIQUIDITY_HOOK',
    address: address('0x16D1560630Ce74af4478d9b8AD46548A092A2000'),
    support: 'DISCOVERY_ONLY',
    evidenceLevel: 'repository_record',
    evidenceUrl: 'https://pair.fund/docs',
  },
  {
    id: 'robinhood.pair.hook-v2-observed',
    network: 'robinhood',
    protocolId: 'UNKNOWN',
    venueId: 'UNISWAP_V4',
    platformId: 'PAIR',
    role: 'PLATFORM_LIQUIDITY_HOOK',
    address: address('0xD2F759A1Cf13c30127C551c3aEe04629Aea200c0'),
    support: 'DISCOVERY_ONLY',
    evidenceLevel: 'repository_record',
    evidenceUrl: 'https://pair.fund/docs',
  },
  {
    id: 'bnb.pancakeswap-v2.factory',
    network: 'bnb',
    protocolId: 'PANCAKESWAP_V2',
    venueId: 'PANCAKESWAP_V2',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V2_SOURCE,
  },
  {
    id: 'bnb.pancakeswap-v2.router',
    network: 'bnb',
    protocolId: 'PANCAKESWAP_V2',
    venueId: 'PANCAKESWAP_V2',
    platformId: null,
    role: 'ROUTER',
    address: address('0x10ED43C718714eb63d5aA57B78B54704E256024E'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V2_SOURCE,
  },
  {
    id: 'bnb.pancakeswap-v3.factory',
    network: 'bnb',
    protocolId: 'PANCAKESWAP_V3',
    venueId: 'PANCAKESWAP_V3',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V3_SOURCE,
  },
  {
    id: 'bnb.pancakeswap-v3.quoter-v2',
    network: 'bnb',
    protocolId: 'PANCAKESWAP_V3',
    venueId: 'PANCAKESWAP_V3',
    platformId: null,
    role: 'QUOTER',
    address: address('0xB048Bbc1Ee6b733FFfCFb9e9CeF7375518e25997'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: PANCAKE_V3_SOURCE,
  },
  {
    id: 'bnb.uniswap-v2.factory',
    network: 'bnb',
    protocolId: 'UNISWAP_V2',
    venueId: 'UNISWAP_V2',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V2_SOURCE,
  },
  {
    id: 'bnb.uniswap-v2.router',
    network: 'bnb',
    protocolId: 'UNISWAP_V2',
    venueId: 'UNISWAP_V2',
    platformId: null,
    role: 'ROUTER',
    address: address('0x4752ba5DBc23f44D87826276BF6Fd6b1C372aD24'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V2_SOURCE,
  },
  {
    id: 'bnb.uniswap-v3.factory',
    network: 'bnb',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'POOL_FACTORY',
    address: address('0xdB1d10011AD0Ff90774D0C6Bb92e5C5c8b4461F7'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_BNB_SOURCE,
  },
  {
    id: 'bnb.uniswap-v3.quoter-v2',
    network: 'bnb',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'QUOTER',
    address: address('0x78D78E420Da98ad378D7799bE8f4AF69033EB077'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_BNB_SOURCE,
  },
  {
    id: 'bnb.uniswap-v3.router',
    network: 'bnb',
    protocolId: 'UNISWAP_V3',
    venueId: 'UNISWAP_V3',
    platformId: null,
    role: 'ROUTER',
    address: address('0xB971eF87ede563556b2ED4b1C0b0019111Dd85d2'),
    support: 'REGISTRY_ONLY',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V3_BNB_SOURCE,
  },
  {
    id: 'bnb.uniswap-v4.pool-manager',
    network: 'bnb',
    protocolId: 'UNISWAP_V4',
    venueId: 'UNISWAP_V4',
    platformId: null,
    role: 'POOL_MANAGER',
    address: address('0x28e2ea090877bf75740558f6bfb36a5ffee9e9df'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V4_SOURCE,
  },
  {
    id: 'bnb.uniswap-v4.quoter',
    network: 'bnb',
    protocolId: 'UNISWAP_V4',
    venueId: 'UNISWAP_V4',
    platformId: null,
    role: 'QUOTER',
    address: address('0x9f75dd27d6664c475b90e105573e550ff69437b0'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V4_SOURCE,
  },
  {
    id: 'bnb.uniswap-v4.state-view',
    network: 'bnb',
    protocolId: 'UNISWAP_V4',
    venueId: 'UNISWAP_V4',
    platformId: null,
    role: 'STATE_VIEW',
    address: address('0xd13dd3d6e93f276fafc9db9e6bb47c1180aee0c4'),
    support: 'PLANNED_ADAPTER',
    evidenceLevel: 'configured',
    evidenceUrl: UNISWAP_V4_SOURCE,
  },
]

export function contractsForNetwork(network: NetworkId): readonly ContractDefinition[] {
  return CONTRACTS.filter((contract) => contract.network === network)
}

export function assertRegistry(): void {
  const ids = new Set<string>()
  const identities = new Set<string>()
  for (const contract of CONTRACTS) {
    if (ids.has(contract.id)) throw new Error(`duplicate contract id: ${contract.id}`)
    ids.add(contract.id)
    const identity = `${NETWORKS[contract.network].chainId}:${contract.address.toLowerCase()}:${contract.role}`
    if (identities.has(identity)) throw new Error(`duplicate contract identity: ${identity}`)
    identities.add(identity)
    if (contract.platformId !== null && contract.venueId === contract.platformId) {
      throw new Error(`platform and venue were collapsed: ${contract.id}`)
    }
  }
}
